<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
  return view('welcome');
});
Route::get('/home', function () {
  return redirect('/');
});
Route::get('/welcome', function () {
  return redirect('/');
});

Route::resource('bugs', 'BugController', ['except' => [
  'destroy'
]]);

Route::post('/comments', 'CommentController@store')->middleware('auth');
//login and register routes generated by laravel
//not invalid?
Auth::routes();
